### ISSUE TITLE
AttributeError: type object 'GroupsRequestBuilder' has no attribute 'GroupsRequestBuilderGetRequestConfiguration'

### ISSUE THREAD

**Issue by Hcoster** [microsoftgraph/msgraph-sdk-python#673]
Issue with version 1.3. Code is working fine with 1.2.0. Trying to retrieve the members of a group with $count and $filter queries. Not able to run this request as I am getting the error above when specifying the query parameters and request configuration.

**Comment by codeforkjeff** [comment]
I'm seeing a similar error that I think is probably related:

```
AttributeError: type object 'ChatsRequestBuilder' has no attribute 'ChatsRequestBuilderGetRequestConfiguration'
```

The relevant code looks something like:

```python
from kiota_abstractions.native_response_handler import NativeResponseHandler
from kiota_http.middleware.options import ResponseHandlerOption
from msgraph.generated.chats.chats_request_builder import ChatsRequestBuilder

query_params = ChatsRequestBuilder.ChatsRequestBuilderGetQueryParameters(
  expand=["members", "lastMessagePreview"],
  top=50
)
request_config = ChatsRequestBuilder.ChatsRequestBuilderGetRequestConfiguration(
  options=[ResponseHandlerOption(NativeResponseHandler())],
  query_parameters = query_params,
)
```

This is in a program that was working fine with 1.2.0.

**Comment by sa01sgSAMS** [comment]
I'm seeing this ( 1.3.0) with both:
SecureScoresRequestBuilder.SecureScoresRequestBuilderGetRequestConfiguration
and
SignInsRequestBuilder.SignInsRequestBuilderGetRequestConfiguration
e.g. "type object 'SignInsRequestBuilder' has no attribute 'SignInsRequestBuilderGetRequestConfiguration'"
I am new to using the MSgraph module, so can;t comment on previous versions

**Comment by yaench** [comment]
I have the same issue with version 1.3.0. Actually with the example code:


```python
from msgraph import GraphServiceClient
from msgraph.generated.groups.groups_request_builder import GroupsRequestBuilder
graph_client = GraphServiceClient(credentials, scopes)
query_params = GroupsRequestBuilder.GroupsRequestBuilderGetQueryParameters(
		filter = "startswith(displayName, 'a')",
		count = True,
		top = 1,
		orderby = ["displayName"],
)

request_configuration = GroupsRequestBuilder.GroupsRequestBuilderGetRequestConfiguration(
query_parameters = query_params,
)
request_configuration.headers.add("ConsistencyLevel", "eventual")
result = await graph_client.groups.get(request_configuration = request_configuration)
```

error
```
AttributeError: type object 'GroupsRequestBuilder' has no attribute 'GroupsRequestBuilderGetRequestConfiguration'
```

Version 1.2.0 works fine.

**Comment by baywet** [comment]
Thanks everyone for using the SDK and reporting this.
While we're working to identify the root cause of the issue, have you tried the following changes?

```diff
+from kiota_abstractions.base_request_configuration import RequestConfiguration
from msgraph import GraphServiceClient
from msgraph.generated.groups.groups_request_builder import GroupsRequestBuilder
graph_client = GraphServiceClient(credentials, scopes)
query_params = GroupsRequestBuilder.GroupsRequestBuilderGetQueryParameters(
		filter = "startswith(displayName, 'a')",
		count = True,
		top = 1,
		orderby = ["displayName"],
)
-request_configuration = GroupsRequestBuilder.GroupsRequestBuilderGetRequestConfiguration(
+request_configuration = RequestConfiguration(
query_parameters = query_params,
)
request_configuration.headers.add("ConsistencyLevel", "eventual")
result = await graph_client.groups.get(request_configuration = request_configuration)
```

**Comment by sa01sgSAMS** [comment]
> Thanks everyone for using the SDK and reporting this. While we're working to identify the root cause of the issue, have you tried the following changes?
> 

Thank you - this works, In my case for:.

```
query_params = SignInsRequestBuilder.SignInsRequestBuilderGetQueryParameters(filter = "createdDateTime ge 2024-04-21T12:00:00Z",)
request_configuration = RequestConfiguration(query_parameters=query_params)
result1=await client.audit_logs.sign_ins.get(request_configuration = request_configuration)
```

 This is not, however, as documented.  Having said that, having a generic method of creating Request configurations, rather than a separate one for each type ( e.g. groups, secure scores, sigins, etc) seems sensible.  Will this be standard going forward ?

**Comment by baywet** [comment]
Thanks for confirming.
We're still getting our bearings due to staff rotation on this issue to understand what was missed and what's the root cause.
But from early analysis results it looks that yes, it'd be the way forward, but somehow the "backward compatible" type is missing from the generation. I.E. we should still be generating a `GroupsRequestBuilderGetRequestConfiguration` but mark it as deprecated/obsolete.
This is pending the validation of this
```python
async def get(self,request_configuration: Optional[UsersRequestBuilderGetRequestConfiguration] = None)
```

is now this

```python
async def get(self,request_configuration: Optional[RequestConfiguration] = None)
```

but should be this instead

```python
async def get(self,request_configuration: Optional[RequestConfiguration[UsersRequestBuilderGetQueryParameters]] = None)
```

(if it's a thing that can even be expressed in Python)

**Comment by shemogumbe** [comment]
On feasibility, yes, but considering deprecating this altogether
`async def get(self,request_configuration: Optional[RequestConfiguration[UsersRequestBuilderGetQueryParameters]] = None)`
 will mean we make `UserRequestBuilderGetQueryParameters` a subclass of `RequestConfiguration`. Currently its a dataclass - which is not allowed to inherit from `RequestConfiguration`

Makes sense to leave it as :
`async def get(self,request_configuration: Optional[UsersRequestBuilderGetRequestConfiguration] = None)`

**Comment by baywet** [comment]
@shemogumbe just to confirm here, you meant `UserRequestBuilderGetRequestConfiguration` not `UserRequestBuilderGetQueryParameters` correct?

**Comment by shemogumbe** [comment]
Ooh yest, `UserRequestRequestConfiguration`, there are no issues with Parameters

**Comment by baywet** [comment]
does that mean we can make it inherit the RequestConfiguration and solve the backward compatibility issues?
