### ISSUE TITLE
How to get children of the root of a Drive?

### ISSUE THREAD

**Issue by champlin2** [microsoftgraph/msgraph-sdk-python#160]
Using 1.0.0a9 I was able to use this line to get the children of the root of a drive:

`children = await (self.app_client.drives_by_id(drive.id).root.children.get())`

but after upgrading to 1.0.0a11 I get "'RootRequestBuilder' object has no attribute 'children'"

**Comment by champlin2** [comment]
@samwelkanda ?

**Comment by champlin2** [comment]
I verified that this GET request works

`https://graph.microsoft.com/v1.0/drives/<drive-id>/root/children`

using the Microsoft Graph Explorer to my tenant but there is no way in the latest release (1.0.0a12) that I can see to send this GET request (seems like it was there in 1.0.0a9).  Can this be rectified as it is preventing us from running our automated tests against out product.

Using 

`await (self.app_client.drives_by_id(drive.id).root.get())`

Gets the root drive item but the .children property is None (when there are children)

@samwelkanda @baywet @isvargasmsft @abetomo @MichaelYochpaz @SilasKenneth

**Comment by samwelkanda** [comment]
HI @champlin2 , in versions > `1.0.0a9`, root is an indexer, which means you can pass it as an argument in the `by_id` call. 

The resulting call to get the children of the root drive would then be `client.drives.by_drive_id('DRIVE_ID').items.by_drive_item_id('root').children.get()`

Please refer to this [sample](https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/samples/drives_samples.md#6-get-items-in-the-root-folder-of-the-drive-get-drivesiditemsrootchildren) for a complete example.

Thanks.

**Comment by samwelkanda** [comment]
Closing this for now, feel free to re-open if you have further questions.

**Comment by champlin2** [comment]
@samwelkanda 

Thank you for the sample code - I went to test it out but it looks like in a12 that sites_by_id() was removed from the base client which is what I was using and then calling drives.get() to get a list of all the drives for the site.

When I call sites.get() the drives doesn't seem to be populated so what do I need to do to get a list of all the drives for a known site (so I can then use the code above to get all the items in the root)?

**Comment by samwelkanda** [comment]
Hey @champlin2 

Indeed the API has changed in `v12`. Indexers are now a step lower so `client.sites_by_id('SITE_ID').get()` is now `client.sites.by_site_id(SITE_ID).get()`.

This was done to remove path conflicts when constructing requests. 

A full example to list drives of a site should be

```py
async def get_site_drives():
    try:
        drives = await client.sites.by_site_id('SITE_ID').drives.get()
        for drive in drives.value:
            print(drive.id, drive.name)
    except Exception as e:
        print(e)
asyncio.run(get_site_drives())
```

**Comment by champlin2** [comment]
@samwelkanda thank you for the help!  Got things working again with the a12 version
