### ISSUE TITLE
Cant connect after upgrade to 1.0.0a13 'GraphRequestAdapter' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by srmo** [microsoftgraph/msgraph-sdk-python#287]
I just upgrade msgraph-sdk from 1.0.0a12 to 1.0.0a13
First, I got errors about kiota-http and kiota-abstraction imports not working. I've reinstalled those packages.
Now I get 
```   
 return await self.request_adapter.send_async(request_info, GroupCollectionResponse, error_mapping)
  File "<...>/venv/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 113, in send_async
    response = await self.get_http_response_message(request_info)
  File "<...>/venv/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 324, in get_http_response_message
    await self._authentication_provider.authenticate_request(request_info)
  File "<...>/venv/lib/python3.9/site-packages/kiota_abstractions/authentication/base_bearer_token_authentication_provider.py", line 27, in authenticate_request
    token = await self.access_token_provider.get_authorization_token(request.url)
  File "<...>/venv/lib/python3.9/site-packages/kiota_authentication_azure/azure_identity_access_token_provider.py", line 49, in get_authorization_token
    if inspect.iscoroutinefunction(self._credentials.get_token):
AttributeError: 'GraphRequestAdapter' object has no attribute 'get_token'
python-BaseException
``` 
on a client.groups.get(..) call

I've used a naive asyncio approach, where my class just gets hold of the event loop via `asyncio.get_event_loop()` and then calls `run_until_complete(<actual call>)`

This worked fine until now.

Then I reinstalled all azure-identity and msgraph-sdk packages. The error persists. With 3.9.17 here.

What am I doing wrong? What should I do?

EDIT: I just tried again with a fresh venv, still the same error

**Comment by srmo** [comment]
Just found the solution. I missed an error/warning in one of my source files. Turns out, I needed to use the named parameter for the GraphServiceClient. 
i.e. `self.user_client = GraphServiceClient(self.adapter)` becomes `self.user_client = GraphServiceClient(request_adapter=self.adapter)`
Found the solution here: https://www.reddit.com/r/learningpython/comments/14rt993/having_difficulty_with_microsoft_graph_api_and/
